In [2]:
'LAB MID Question'

Name= "A.J.M Istiaqu"
ID="23341065"
Section="12"
Time = "40 Minutes"

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from itertools import combinations
from numpy.polynomial import Polynomial

Q1. [3 marks] Display a polynomial of appropriate degree which is given below:

$(x+6)(x^3-2)(x-1)$

**Hints: Use built-in Polynomial class.**

Also compute the approximate value of polynomial at x=6.



In [7]:
#Q1
#Use built-in Polynomial class
coeff= [12, -10, -2, -6, 5, 1]
p= Polynomial(coeff)
display(p)

x=6
value=p(x)
print(value)

Polynomial([ 12., -10.,  -2.,  -6.,   5.,   1.], domain=[-1,  1], window=[-1,  1], symbol='x')

12840.0


Q2. [3 marks] We know standard format of polynomial of degree 3 :

$P(x)= a_0 + a_1x + a_2x^2 + a_3x^3$

But you have to create a different version of polynomial which is given below:

$P(x)= a_3 + a_2x + a_1x^2 + a_0x^3$

Then find approximate value of your created polynomial at x=2

Coefficients are given $[a_0,a_1,a_2,a_
3]=[2,4,6,8]$

In [9]:
#Q2
coeff=[2,4,6,8]
n= len(coeff)
px=0
x=2
#use a loop to find value of px at x
for i in range(n):
  px += coeff[i] * (x ** (n - 1 - i))

print(px)

52


Q3. [3 marks] You all know the formula of Lagrange basis. But Messi created another basis which is called Leo basis. the formula of this basis is given below:

\begin{equation}
L_m(x) = \prod_{j=0,j\neq m}^{n} \frac{x-x_j}{(x_m-x_j)^2}
\end{equation}

In [10]:
#Q3
#node_x means an array of nodes, x means a value, t means a value
def leo(m, node_x, x):
  L_m= 1 #initialization
  #Use a loop to find basis
  for j in range(len(node_x)):
    if j != m:
      L_m *= (x - node_x[j]) / ((node_x[m] - node_x[j]) ** 2)

  return L_m

In [11]:
#Q3
#Tester code
node_x=[1,2,3,4]
x=6
print(leo(1,node_x,x))



7.5


Q4. [3 marks] Suppose, you have 3 nodes($x_0$, $x_1$, $x_2$). We know standard format of Vandermonde matrix looks like:

$$[[x_0^0, x_0^1, x_0^2]$$

 $$[x_1^0, x_1^1, x_1^2]$$

 $$[x_2^0, x_2^1, x_2^2]]$$

 But you have to create a modified version of this matrix which should look like:

 $$[[x_0^3, x_0^2, x_0^1]$$

 $$[x_1^3, x_1^2, x_1^1]$$

$$[x_2^3, x_2^2, x_2^1]]$$


In [16]:
#Q4
nodes = [1,2,3]
n = len(nodes)-1

#fill up dimention
V = np.zeros((n+1,n+1))

#compute V matrix
#your code here
for i in range(n + 1):
  for j in range(n + 1):
    V[i, j] = nodes[i] ** (n-j+1)
print(V)

#Answer should look like:
# [[1,1,1]
#  [8,4,2]
#  [27,9,3]]

[[ 1.  1.  1.]
 [ 8.  4.  2.]
 [27.  9.  3.]]


Q5. [3 marks] Given the nodes (1,1.2),(3,3.6),(5,6), (11,13.2),

Compute the value of F(x) where n+1 is the number of nodes.

\begin{equation}
f(x) = \sum_{i=0}^{n} \frac{x_i * y_i}{x-x_i}
\end{equation}

In [17]:
#Q5
data_x = [1, 3, 5, 11]
data_y = [1.2, 3.6, 6, 13.2]

def func(x):
  f = 0.0
  n = len(data_x) - 1
  for i in range(n + 1):
    numerator = data_y[i]
    denominator = 1.0
    for j in range(n + 1):
      if j != i:
        denominator *= (data_x[i] - data_x[j])
    f += numerator / denominator
  return f

In [18]:
#Q5
#this displayes the answer

print(func(5))

3.469446951953614e-18
